rabbitmq.host=localhost
rabbitmq.port=5672
rabbitmq.user=guest
rabbitmq.password=guest
rabbitmq.queue.bo1=queue.sales.bo1
rabbitmq.queue.bo2=queue.sales.bo2

db.bo1.url=jdbc:mysql://localhost:3306/sales_bo1?serverTimezone=UTC
db.bo1.user=root
db.bo1.password=

db.bo2.url=jdbc:mysql://localhost:3306/sales_bo2?serverTimezone=UTC
db.bo2.user=root
db.bo2.password=

db.ho.url=jdbc:mysql://localhost:3306/sales_ho?serverTimezone=UTC
db.ho.user=root
db.ho.password=
